package main

import (
	"bufio"
	"context"
	"fmt"
	"os"
	"reflect"
	"strings"
	"testing"

	"github.com/containerd/nri/pkg/api"
	"k8s.io/utils/cpuset"
)

// cpuRange is a small helper for building expected CPU slices.
func cpuRange(lo, hi int) []int {
	out := make([]int, 0, hi-lo+1)
	for i := lo; i <= hi; i++ {
		out = append(out, i)
	}
	return out
}

const goldenVectorFile = "testdata/hwloc-masks.tsv"

type maskVector struct {
	name string
	mask string
	cpus []int
}

// loadGoldenVectors reads the hwloc-derived mask fixtures.
//
// The fixture is generated by hack/gen_hwloc_vectors.py, which asks hwloc itself for
// the mask of a known PU set on a synthetic 512-PU topology. That matters because
// hwloc's bitmask grammar is not obvious: fields are 32 bits wide, comma separated,
// printed MOST SIGNIFICANT FIRST, and runs of all-zero fields are compressed to
// empty fields (one empty field per zero group). Hand-written vectors would just
// re-encode whatever we assumed the format was, which is how the original
// single-ParseUint implementation shipped.
func loadGoldenVectors(t *testing.T) []maskVector {
	t.Helper()

	f, err := os.Open(goldenVectorFile)
	if err != nil {
		t.Fatalf("cannot open %s (regenerate with hack/gen_hwloc_vectors.py): %v", goldenVectorFile, err)
	}
	defer f.Close()

	var vectors []maskVector
	scanner := bufio.NewScanner(f)
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for line := 1; scanner.Scan(); line++ {
		text := scanner.Text()
		if strings.TrimSpace(text) == "" || strings.HasPrefix(text, "#") {
			continue
		}
		parts := strings.Split(text, "\t")
		if len(parts) != 3 {
			t.Fatalf("%s:%d: expected 3 tab separated columns, got %d", goldenVectorFile, line, len(parts))
		}
		set, err := cpuset.Parse(parts[2])
		if err != nil {
			t.Fatalf("%s:%d: expected cpu list %q is not parseable: %v", goldenVectorFile, line, parts[2], err)
		}
		vectors = append(vectors, maskVector{name: parts[0], mask: parts[1], cpus: set.List()})
	}
	if err := scanner.Err(); err != nil {
		t.Fatalf("reading %s: %v", goldenVectorFile, err)
	}
	if len(vectors) == 0 {
		t.Fatalf("%s contained no vectors", goldenVectorFile)
	}
	return vectors
}

func TestParseHwlocMaskGoldenVectors(t *testing.T) {
	for _, tc := range loadGoldenVectors(t) {
		t.Run(tc.name, func(t *testing.T) {
			got, err := parseHwlocMask(tc.mask)
			if err != nil {
				t.Fatalf("parseHwlocMask(%q) returned an unexpected error: %v", tc.mask, err)
			}
			if !reflect.DeepEqual(got, tc.cpus) {
				t.Errorf("parseHwlocMask(%q)\n  got  %v\n  want %v", tc.mask, got, tc.cpus)
			}
		})
	}
}

// Every golden mask must also survive the format-dispatching entry point.
func TestParseCPUSpecHandlesEveryGoldenMask(t *testing.T) {
	for _, tc := range loadGoldenVectors(t) {
		t.Run(tc.name, func(t *testing.T) {
			got, err := parseCPUSpec(tc.mask)
			if err != nil {
				t.Fatalf("parseCPUSpec(%q) returned an unexpected error: %v", tc.mask, err)
			}
			if !reflect.DeepEqual(got, tc.cpus) {
				t.Errorf("parseCPUSpec(%q)\n  got  %v\n  want %v", tc.mask, got, tc.cpus)
			}
		})
	}
}

// TestParseHwlocMaskRegressionAboveCPU63 pins the specific bug this change fixes.
// The previous implementation ran strconv.ParseUint on the entire mask string with
// bitSize 64, so every one of these inputs errored out and the container was left
// completely unbound with only a log line.
func TestParseHwlocMaskRegressionAboveCPU63(t *testing.T) {
	masks := []string{
		"0x00000001,,0x0",
		"0x0000000f,,0x0",
		"0x00000100,,,,,,0x0",
		"0x80000000,,,,,,,,,,,,,,,0x0",
	}
	for _, mask := range masks {
		cpus, err := parseHwlocMask(mask)
		if err != nil {
			t.Errorf("mask %q should parse but failed: %v", mask, err)
			continue
		}
		if len(cpus) == 0 {
			t.Errorf("mask %q parsed to an empty CPU set", mask)
			continue
		}
		if cpus[len(cpus)-1] <= 63 {
			t.Errorf("mask %q should select a CPU above index 63, got %v", mask, cpus)
		}
	}
}

func TestParseHwlocMaskRejectsMalformed(t *testing.T) {
	tests := []struct {
		name string
		mask string
	}{
		{"empty", ""},
		{"whitespace only", "   "},
		{"zero mask selects nothing", "0x0"},
		{"all compressed zero groups", "0x0,,,0x0"},
		{"not hex", "0xzzzz"},
		{"prefix with no digits", "0x,0x1"},
		{"field too wide to place", "0xffffffffffffffff,0x0"},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			if cpus, err := parseHwlocMask(tc.mask); err == nil {
				t.Errorf("parseHwlocMask(%q) should have failed, got %v", tc.mask, cpus)
			}
		})
	}
}

// A single field is positionally unambiguous, so we still accept one wide word for
// compatibility with tools that print a 64-bit mask.
func TestParseHwlocMaskAcceptsSingleWideField(t *testing.T) {
	got, err := parseHwlocMask("0xffffffffffffffff")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if want := cpuRange(0, 63); !reflect.DeepEqual(got, want) {
		t.Errorf("got %v, want %v", got, want)
	}
}

func TestParseCPUSpecAcceptsCPULists(t *testing.T) {
	tests := []struct {
		spec string
		want []int
	}{
		{"0", []int{0}},
		{"0-3", []int{0, 1, 2, 3}},
		{"0-3,64-67", []int{0, 1, 2, 3, 64, 65, 66, 67}},
		{"511", []int{511}},
		{" 5,137 ", []int{5, 137}},
	}
	for _, tc := range tests {
		t.Run(tc.spec, func(t *testing.T) {
			got, err := parseCPUSpec(tc.spec)
			if err != nil {
				t.Fatalf("parseCPUSpec(%q) failed: %v", tc.spec, err)
			}
			if !reflect.DeepEqual(got, tc.want) {
				t.Errorf("parseCPUSpec(%q) = %v, want %v", tc.spec, got, tc.want)
			}
		})
	}
}

func TestParseCPUSpecDispatchesOnFormat(t *testing.T) {
	// "0x0000000f,,0x0" must be read as a mask (CPUs 64-67), not as a CPU list.
	got, err := parseCPUSpec("0x0000000f,,0x0")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if want := []int{64, 65, 66, 67}; !reflect.DeepEqual(got, want) {
		t.Errorf("got %v, want %v", got, want)
	}
}

func TestParseCPUSpecRejectsGarbage(t *testing.T) {
	for _, spec := range []string{"", "   ", "not-a-cpu-list", "1-", "-4", "3-1"} {
		if cpus, err := parseCPUSpec(spec); err == nil {
			t.Errorf("parseCPUSpec(%q) should have failed, got %v", spec, cpus)
		}
	}
}

// TestOrderedCPUListPreservesOrder pins the second bug this change fixes. The old
// code reversed a slice and then rendered it through cpuset.CPUSet, whose String()
// method sorts, so the reversal was silently discarded.
func TestOrderedCPUListPreservesOrder(t *testing.T) {
	cpus := []int{64, 65, 66, 67}

	if got, want := orderedCPUList(cpus, false), "64,65,66,67"; got != want {
		t.Errorf("forward order: got %q, want %q", got, want)
	}
	if got, want := orderedCPUList(cpus, true), "67,66,65,64"; got != want {
		t.Errorf("reversed order: got %q, want %q", got, want)
	}
}

func TestOrderedCPUListDoesNotMutateInput(t *testing.T) {
	cpus := []int{1, 2, 3}
	_ = orderedCPUList(cpus, true)
	if want := []int{1, 2, 3}; !reflect.DeepEqual(cpus, want) {
		t.Errorf("input was mutated: got %v, want %v", cpus, want)
	}
}

// --- CreateContainer behaviour ---

func container(name string, env ...string) *api.Container {
	return &api.Container{Name: name, Env: env}
}

func pod() *api.PodSandbox {
	return &api.PodSandbox{Namespace: "default", Name: "fluxbind-pod"}
}

func envFromAdjustment(t *testing.T, adj *api.ContainerAdjustment, key string) (string, bool) {
	t.Helper()
	for _, kv := range adj.Env {
		if kv.Key == key {
			return kv.Value, true
		}
	}
	return "", false
}

func TestCreateContainerAppliesCpusetAndOrder(t *testing.T) {
	tests := []struct {
		name      string
		env       []string
		wantCpus  string
		wantOrder string
	}{
		{
			name:      "low mask",
			env:       []string{"FLUXBIND_CPUSET=0x0000000f"},
			wantCpus:  "0-3",
			wantOrder: "0,1,2,3",
		},
		{
			name:      "mask above cpu 63",
			env:       []string{"FLUXBIND_CPUSET=0x0000000f,,0x0"},
			wantCpus:  "64-67",
			wantOrder: "64,65,66,67",
		},
		{
			name:      "reversal changes order but not the cgroup set",
			env:       []string{"FLUXBIND_CPUSET=0x0000000f,,0x0", "FLUXBIND_CPUSET_REVERSED=yes"},
			wantCpus:  "64-67",
			wantOrder: "67,66,65,64",
		},
		{
			name:      "cpu list input",
			env:       []string{"FLUXBIND_CPUSET=0-3,64-67"},
			wantCpus:  "0-3,64-67",
			wantOrder: "0,1,2,3,64,65,66,67",
		},
		{
			name:      "sparse mask is rendered as a canonical set",
			env:       []string{"FLUXBIND_CPUSET=0x00000001,0x80000000,0x0"},
			wantCpus:  "63-64",
			wantOrder: "63,64",
		},
	}

	d := &Driver{pluginName: "fluxbind"}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			adj, _, err := d.CreateContainer(context.Background(), pod(), container("c", tc.env...))
			if err != nil {
				t.Fatalf("CreateContainer returned an error: %v", err)
			}
			if adj == nil || adj.Linux == nil || adj.Linux.Resources == nil || adj.Linux.Resources.Cpu == nil {
				t.Fatalf("adjustment did not carry a CPU resource block: %+v", adj)
			}
			if got := adj.Linux.Resources.Cpu.Cpus; got != tc.wantCpus {
				t.Errorf("cpuset.cpus = %q, want %q", got, tc.wantCpus)
			}
			order, ok := envFromAdjustment(t, adj, cpuOrderEnvVar)
			if !ok {
				t.Fatalf("%s was not injected", cpuOrderEnvVar)
			}
			if order != tc.wantOrder {
				t.Errorf("%s = %q, want %q", cpuOrderEnvVar, order, tc.wantOrder)
			}
		})
	}
}

func TestCreateContainerIsNoopWithoutEnvVar(t *testing.T) {
	d := &Driver{pluginName: "fluxbind"}
	adj, updates, err := d.CreateContainer(context.Background(), pod(), container("c", "PATH=/usr/bin"))
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if updates != nil {
		t.Errorf("expected no container updates, got %v", updates)
	}
	if adj == nil {
		t.Fatal("expected a non-nil adjustment")
	}
	if adj.Linux != nil {
		t.Errorf("expected no linux adjustment, got %+v", adj.Linux)
	}
	if len(adj.Env) != 0 {
		t.Errorf("expected no env adjustment, got %v", adj.Env)
	}
}

// A malformed mask must fail the container rather than silently starting it
// unbound on the whole machine.
func TestCreateContainerFailsLoudlyOnUnparseableSpec(t *testing.T) {
	d := &Driver{pluginName: "fluxbind"}
	for _, spec := range []string{"0x0", "0xzzz", "garbage", "0xffffffffffffffff,0x0"} {
		t.Run(spec, func(t *testing.T) {
			adj, _, err := d.CreateContainer(context.Background(), pod(),
				container("c", fmt.Sprintf("FLUXBIND_CPUSET=%s", spec)))
			if err == nil {
				t.Fatalf("expected an error for spec %q, got adjustment %+v", spec, adj)
			}
			if adj != nil {
				t.Errorf("expected a nil adjustment alongside the error, got %+v", adj)
			}
		})
	}
}

func TestFindCpusetInEnv(t *testing.T) {
	d := &Driver{}
	tests := []struct {
		name         string
		env          []string
		wantSpec     string
		wantReversed bool
	}{
		{"absent", []string{"PATH=/bin"}, "", false},
		{"nil env", nil, "", false},
		{"plain", []string{"FLUXBIND_CPUSET=0x1"}, "0x1", false},
		{"reversed yes", []string{"FLUXBIND_CPUSET=0x1", "FLUXBIND_CPUSET_REVERSED=yes"}, "0x1", true},
		{"reversed true", []string{"FLUXBIND_CPUSET=0x1", "FLUXBIND_CPUSET_REVERSED=true"}, "0x1", true},
		{"reversed 1", []string{"FLUXBIND_CPUSET=0x1", "FLUXBIND_CPUSET_REVERSED=1"}, "0x1", true},
		{"reversed no", []string{"FLUXBIND_CPUSET=0x1", "FLUXBIND_CPUSET_REVERSED=no"}, "0x1", false},
		{"whitespace trimmed", []string{"FLUXBIND_CPUSET= 0x1 "}, "0x1", false},
		{"prefix collision ignored", []string{"FLUXBIND_CPUSET_OTHER=nope", "FLUXBIND_CPUSET=0x2"}, "0x2", false},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			spec, reversed := d.findCpusetInEnv(container("c", tc.env...))
			if spec != tc.wantSpec || reversed != tc.wantReversed {
				t.Errorf("got (%q, %v), want (%q, %v)", spec, reversed, tc.wantSpec, tc.wantReversed)
			}
		})
	}
}

// The plugin should subscribe only to CreateContainer. Returning a zero mask makes
// the stub infer the mask from every implemented handler, which puts this plugin on
// the synchronous path for every container lifecycle event on the node.
func TestConfigureSubscribesOnlyToCreateContainer(t *testing.T) {
	d := &Driver{}
	mask, err := d.Configure(context.Background(), "", "containerd", "2.0")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if want := api.MustParseEventMask("CreateContainer"); mask != want {
		t.Errorf("event mask = %v, want %v", mask, want)
	}
	if mask == 0 {
		t.Error("event mask must not be zero")
	}
}
