# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import warnings

import grpc

from fluxbind_dra.proto.dra import \
    dra_pb2 as fluxbind__dra_dot_proto_dot_dra_dot_dra__pb2

GRPC_GENERATED_VERSION = "1.68.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in fluxbind_dra/proto/dra/dra_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class DRAPluginStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NodePrepareResources = channel.unary_unary(
            "/k8s.io.kubelet.pkg.apis.dra.v1beta1.DRAPlugin/NodePrepareResources",
            request_serializer=fluxbind__dra_dot_proto_dot_dra_dot_dra__pb2.NodePrepareResourcesRequest.SerializeToString,
            response_deserializer=fluxbind__dra_dot_proto_dot_dra_dot_dra__pb2.NodePrepareResourcesResponse.FromString,
            _registered_method=True,
        )
        self.NodeUnprepareResources = channel.unary_unary(
            "/k8s.io.kubelet.pkg.apis.dra.v1beta1.DRAPlugin/NodeUnprepareResources",
            request_serializer=fluxbind__dra_dot_proto_dot_dra_dot_dra__pb2.NodeUnprepareResourcesRequest.SerializeToString,
            response_deserializer=fluxbind__dra_dot_proto_dot_dra_dot_dra__pb2.NodeUnprepareResourcesResponse.FromString,
            _registered_method=True,
        )


class DRAPluginServicer(object):
    """Missing associated documentation comment in .proto file."""

    def NodePrepareResources(self, request, context):
        """NodePrepareResources prepares several ResourceClaims
        for use on the node. If an error is returned, the
        response is ignored. Failures for individual claims
        can be reported inside NodePrepareResourcesResponse.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def NodeUnprepareResources(self, request, context):
        """NodeUnprepareResources is the opposite of NodePrepareResources.
        The same error handling rules apply,
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_DRAPluginServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "NodePrepareResources": grpc.unary_unary_rpc_method_handler(
            servicer.NodePrepareResources,
            request_deserializer=fluxbind__dra_dot_proto_dot_dra_dot_dra__pb2.NodePrepareResourcesRequest.FromString,
            response_serializer=fluxbind__dra_dot_proto_dot_dra_dot_dra__pb2.NodePrepareResourcesResponse.SerializeToString,
        ),
        "NodeUnprepareResources": grpc.unary_unary_rpc_method_handler(
            servicer.NodeUnprepareResources,
            request_deserializer=fluxbind__dra_dot_proto_dot_dra_dot_dra__pb2.NodeUnprepareResourcesRequest.FromString,
            response_serializer=fluxbind__dra_dot_proto_dot_dra_dot_dra__pb2.NodeUnprepareResourcesResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "k8s.io.kubelet.pkg.apis.dra.v1beta1.DRAPlugin", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "k8s.io.kubelet.pkg.apis.dra.v1beta1.DRAPlugin", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class DRAPlugin(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def NodePrepareResources(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/k8s.io.kubelet.pkg.apis.dra.v1beta1.DRAPlugin/NodePrepareResources",
            fluxbind__dra_dot_proto_dot_dra_dot_dra__pb2.NodePrepareResourcesRequest.SerializeToString,
            fluxbind__dra_dot_proto_dot_dra_dot_dra__pb2.NodePrepareResourcesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def NodeUnprepareResources(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/k8s.io.kubelet.pkg.apis.dra.v1beta1.DRAPlugin/NodeUnprepareResources",
            fluxbind__dra_dot_proto_dot_dra_dot_dra__pb2.NodeUnprepareResourcesRequest.SerializeToString,
            fluxbind__dra_dot_proto_dot_dra_dot_dra__pb2.NodeUnprepareResourcesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
