# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from fluxbind_dra.proto.nri import api_pb2 as fluxbind__dra_dot_proto_dot_nri_dot_api__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in fluxbind_dra/proto/nri/api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RuntimeStub(object):
    """Runtime service is the public API runtimes expose for NRI plugins.
    On this interface RPC requests are initiated by the plugin. This
    only covers plugin registration and unsolicited container updates.
    The rest of the API is defined by the Plugin service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterPlugin = channel.unary_unary(
                '/nri.pkg.api.v1alpha1.Runtime/RegisterPlugin',
                request_serializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.RegisterPluginRequest.SerializeToString,
                response_deserializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.Empty.FromString,
                _registered_method=True)
        self.UpdateContainers = channel.unary_unary(
                '/nri.pkg.api.v1alpha1.Runtime/UpdateContainers',
                request_serializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.UpdateContainersRequest.SerializeToString,
                response_deserializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.UpdateContainersResponse.FromString,
                _registered_method=True)


class RuntimeServicer(object):
    """Runtime service is the public API runtimes expose for NRI plugins.
    On this interface RPC requests are initiated by the plugin. This
    only covers plugin registration and unsolicited container updates.
    The rest of the API is defined by the Plugin service.
    """

    def RegisterPlugin(self, request, context):
        """RegisterPlugin registers the plugin with the runtime.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateContainers(self, request, context):
        """UpdateContainers requests unsolicited updates to a set of containers.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RuntimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterPlugin': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterPlugin,
                    request_deserializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.RegisterPluginRequest.FromString,
                    response_serializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.Empty.SerializeToString,
            ),
            'UpdateContainers': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateContainers,
                    request_deserializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.UpdateContainersRequest.FromString,
                    response_serializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.UpdateContainersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nri.pkg.api.v1alpha1.Runtime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nri.pkg.api.v1alpha1.Runtime', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Runtime(object):
    """Runtime service is the public API runtimes expose for NRI plugins.
    On this interface RPC requests are initiated by the plugin. This
    only covers plugin registration and unsolicited container updates.
    The rest of the API is defined by the Plugin service.
    """

    @staticmethod
    def RegisterPlugin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nri.pkg.api.v1alpha1.Runtime/RegisterPlugin',
            fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.RegisterPluginRequest.SerializeToString,
            fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateContainers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nri.pkg.api.v1alpha1.Runtime/UpdateContainers',
            fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.UpdateContainersRequest.SerializeToString,
            fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.UpdateContainersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PluginStub(object):
    """
    Plugin is the API NRI uses to interact with plugins. It is used to
    - configure a plugin and subscribe it for lifecycle events
    - synchronize the state of a plugin with that of the runtime
    - hook a plugin into the lifecycle events of its interest

    During configuration the plugin tells the runtime which lifecycle events
    it wishes to get hooked into. Once configured, the plugin is synchronized
    with the runtime by receiving the list of pods and containers known to
    the runtime. The plugin can request changes to any of the containers in
    response. After initial synchronization the plugin starts receiving the
    events it subscribed for as they occur in the runtime. For container
    creation, update, and stop events, the plugin can request changes, both
    to the container that triggered the event or any other existing container
    in the runtime.

    For a subset of the container lifecycle events, NRI defines an additional
    Post-variant of the event. These variants are defined for CreateContainer,
    StartContainer, and UpdateContainer. For creation and update, these events
    can be used by plugins to discover the full extent of changes applied to
    the container, including any changes made by other active plugins.

    go:plugin type=plugin version=1
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Configure = channel.unary_unary(
                '/nri.pkg.api.v1alpha1.Plugin/Configure',
                request_serializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.ConfigureRequest.SerializeToString,
                response_deserializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.ConfigureResponse.FromString,
                _registered_method=True)
        self.Synchronize = channel.unary_unary(
                '/nri.pkg.api.v1alpha1.Plugin/Synchronize',
                request_serializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.SynchronizeRequest.SerializeToString,
                response_deserializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.SynchronizeResponse.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/nri.pkg.api.v1alpha1.Plugin/Shutdown',
                request_serializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.Empty.SerializeToString,
                response_deserializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.Empty.FromString,
                _registered_method=True)
        self.CreateContainer = channel.unary_unary(
                '/nri.pkg.api.v1alpha1.Plugin/CreateContainer',
                request_serializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.CreateContainerRequest.SerializeToString,
                response_deserializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.CreateContainerResponse.FromString,
                _registered_method=True)
        self.UpdateContainer = channel.unary_unary(
                '/nri.pkg.api.v1alpha1.Plugin/UpdateContainer',
                request_serializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.UpdateContainerRequest.SerializeToString,
                response_deserializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.UpdateContainerResponse.FromString,
                _registered_method=True)
        self.StopContainer = channel.unary_unary(
                '/nri.pkg.api.v1alpha1.Plugin/StopContainer',
                request_serializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.StopContainerRequest.SerializeToString,
                response_deserializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.StopContainerResponse.FromString,
                _registered_method=True)
        self.UpdatePodSandbox = channel.unary_unary(
                '/nri.pkg.api.v1alpha1.Plugin/UpdatePodSandbox',
                request_serializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.UpdatePodSandboxRequest.SerializeToString,
                response_deserializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.UpdatePodSandboxResponse.FromString,
                _registered_method=True)
        self.StateChange = channel.unary_unary(
                '/nri.pkg.api.v1alpha1.Plugin/StateChange',
                request_serializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.StateChangeEvent.SerializeToString,
                response_deserializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.Empty.FromString,
                _registered_method=True)
        self.ValidateContainerAdjustment = channel.unary_unary(
                '/nri.pkg.api.v1alpha1.Plugin/ValidateContainerAdjustment',
                request_serializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.ValidateContainerAdjustmentRequest.SerializeToString,
                response_deserializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.ValidateContainerAdjustmentResponse.FromString,
                _registered_method=True)


class PluginServicer(object):
    """
    Plugin is the API NRI uses to interact with plugins. It is used to
    - configure a plugin and subscribe it for lifecycle events
    - synchronize the state of a plugin with that of the runtime
    - hook a plugin into the lifecycle events of its interest

    During configuration the plugin tells the runtime which lifecycle events
    it wishes to get hooked into. Once configured, the plugin is synchronized
    with the runtime by receiving the list of pods and containers known to
    the runtime. The plugin can request changes to any of the containers in
    response. After initial synchronization the plugin starts receiving the
    events it subscribed for as they occur in the runtime. For container
    creation, update, and stop events, the plugin can request changes, both
    to the container that triggered the event or any other existing container
    in the runtime.

    For a subset of the container lifecycle events, NRI defines an additional
    Post-variant of the event. These variants are defined for CreateContainer,
    StartContainer, and UpdateContainer. For creation and update, these events
    can be used by plugins to discover the full extent of changes applied to
    the container, including any changes made by other active plugins.

    go:plugin type=plugin version=1
    """

    def Configure(self, request, context):
        """Configure the plugin and get its event subscription.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Synchronize(self, request, context):
        """Synchronize the plugin with the state of the runtime.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Shutdown a plugin (let it know the runtime is going down).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateContainer(self, request, context):
        """CreateContainer relays the corresponding request to the plugin. In
        response, the plugin can adjust the container being created, and
        update other containers in the runtime. Container adjustment can
        alter labels, annotations, mounts, devices, environment variables,
        OCI hooks, and assigned container resources. Updates can alter
        assigned container resources.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateContainer(self, request, context):
        """UpdateContainer relays the corresponding request to the plugin.
        The plugin can alter how the container is updated and request updates
        to additional containers in the runtime.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopContainer(self, request, context):
        """StopContainer relays the corresponding request to the plugin. The plugin
        can update any of the remaining containers in the runtime in response.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePodSandbox(self, request, context):
        """UpdatePodSandbox relays the corresponding request to the plugin.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StateChange(self, request, context):
        """StateChange relays any remaining pod or container lifecycle/state change
        events the plugin has subscribed for. These can be used to trigger any
        plugin-specific processing which needs to occur in connection with any of
        these events.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateContainerAdjustment(self, request, context):
        """ValidateContainerAdjustment relays a container adjustment validation request
        to the plugin. Container creation will fail the plugin rejects the adjustments.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PluginServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Configure': grpc.unary_unary_rpc_method_handler(
                    servicer.Configure,
                    request_deserializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.ConfigureRequest.FromString,
                    response_serializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.ConfigureResponse.SerializeToString,
            ),
            'Synchronize': grpc.unary_unary_rpc_method_handler(
                    servicer.Synchronize,
                    request_deserializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.SynchronizeRequest.FromString,
                    response_serializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.SynchronizeResponse.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.Empty.FromString,
                    response_serializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.Empty.SerializeToString,
            ),
            'CreateContainer': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateContainer,
                    request_deserializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.CreateContainerRequest.FromString,
                    response_serializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.CreateContainerResponse.SerializeToString,
            ),
            'UpdateContainer': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateContainer,
                    request_deserializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.UpdateContainerRequest.FromString,
                    response_serializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.UpdateContainerResponse.SerializeToString,
            ),
            'StopContainer': grpc.unary_unary_rpc_method_handler(
                    servicer.StopContainer,
                    request_deserializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.StopContainerRequest.FromString,
                    response_serializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.StopContainerResponse.SerializeToString,
            ),
            'UpdatePodSandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePodSandbox,
                    request_deserializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.UpdatePodSandboxRequest.FromString,
                    response_serializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.UpdatePodSandboxResponse.SerializeToString,
            ),
            'StateChange': grpc.unary_unary_rpc_method_handler(
                    servicer.StateChange,
                    request_deserializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.StateChangeEvent.FromString,
                    response_serializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.Empty.SerializeToString,
            ),
            'ValidateContainerAdjustment': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateContainerAdjustment,
                    request_deserializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.ValidateContainerAdjustmentRequest.FromString,
                    response_serializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.ValidateContainerAdjustmentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nri.pkg.api.v1alpha1.Plugin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nri.pkg.api.v1alpha1.Plugin', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Plugin(object):
    """
    Plugin is the API NRI uses to interact with plugins. It is used to
    - configure a plugin and subscribe it for lifecycle events
    - synchronize the state of a plugin with that of the runtime
    - hook a plugin into the lifecycle events of its interest

    During configuration the plugin tells the runtime which lifecycle events
    it wishes to get hooked into. Once configured, the plugin is synchronized
    with the runtime by receiving the list of pods and containers known to
    the runtime. The plugin can request changes to any of the containers in
    response. After initial synchronization the plugin starts receiving the
    events it subscribed for as they occur in the runtime. For container
    creation, update, and stop events, the plugin can request changes, both
    to the container that triggered the event or any other existing container
    in the runtime.

    For a subset of the container lifecycle events, NRI defines an additional
    Post-variant of the event. These variants are defined for CreateContainer,
    StartContainer, and UpdateContainer. For creation and update, these events
    can be used by plugins to discover the full extent of changes applied to
    the container, including any changes made by other active plugins.

    go:plugin type=plugin version=1
    """

    @staticmethod
    def Configure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nri.pkg.api.v1alpha1.Plugin/Configure',
            fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.ConfigureRequest.SerializeToString,
            fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.ConfigureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Synchronize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nri.pkg.api.v1alpha1.Plugin/Synchronize',
            fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.SynchronizeRequest.SerializeToString,
            fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.SynchronizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nri.pkg.api.v1alpha1.Plugin/Shutdown',
            fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.Empty.SerializeToString,
            fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateContainer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nri.pkg.api.v1alpha1.Plugin/CreateContainer',
            fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.CreateContainerRequest.SerializeToString,
            fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.CreateContainerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateContainer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nri.pkg.api.v1alpha1.Plugin/UpdateContainer',
            fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.UpdateContainerRequest.SerializeToString,
            fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.UpdateContainerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopContainer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nri.pkg.api.v1alpha1.Plugin/StopContainer',
            fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.StopContainerRequest.SerializeToString,
            fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.StopContainerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePodSandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nri.pkg.api.v1alpha1.Plugin/UpdatePodSandbox',
            fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.UpdatePodSandboxRequest.SerializeToString,
            fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.UpdatePodSandboxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StateChange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nri.pkg.api.v1alpha1.Plugin/StateChange',
            fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.StateChangeEvent.SerializeToString,
            fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateContainerAdjustment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nri.pkg.api.v1alpha1.Plugin/ValidateContainerAdjustment',
            fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.ValidateContainerAdjustmentRequest.SerializeToString,
            fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.ValidateContainerAdjustmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class HostFunctionsStub(object):
    """go:plugin type=host
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Log = channel.unary_unary(
                '/nri.pkg.api.v1alpha1.HostFunctions/Log',
                request_serializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.LogRequest.SerializeToString,
                response_deserializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.Empty.FromString,
                _registered_method=True)


class HostFunctionsServicer(object):
    """go:plugin type=host
    """

    def Log(self, request, context):
        """Log displays a log message
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HostFunctionsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Log': grpc.unary_unary_rpc_method_handler(
                    servicer.Log,
                    request_deserializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.LogRequest.FromString,
                    response_serializer=fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nri.pkg.api.v1alpha1.HostFunctions', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nri.pkg.api.v1alpha1.HostFunctions', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HostFunctions(object):
    """go:plugin type=host
    """

    @staticmethod
    def Log(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nri.pkg.api.v1alpha1.HostFunctions/Log',
            fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.LogRequest.SerializeToString,
            fluxbind__dra_dot_proto_dot_nri_dot_api__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
