# This file demonstrates the recommended pattern for requesting an ad-hoc,
# user-defined shape with the fluxbind DRA driver.

# Create a ResourceClaim to request the shape.
apiVersion: resource.k8s.io/v1
kind: ResourceClaim
metadata:
  name: cores-shape-claim
spec:
  devices:
    requests:
    - name: "shape-request"
      exactly:
        deviceClassName: "shape"
        count: 1
    config:
      - requests:
        - "shape-request" 
        opaque:
          driver: "fluxbind"
          parameters:
            # Request 4 CPU that are scattered
            resources:
            - type: "core"
              count: 4
              reverse: true
---
# Pod consumes the pre-created ResourceClaim by name.
apiVersion: v1
kind: Pod
metadata:
  name: fluxbind-pod
spec:
  # The Pod's resource request is just a reference to the claim object.
  resourceClaims:
  - name: pod-resources
    resourceClaimName: cores-shape-claim
    
  containers:
  - name: test-container
    image: ghcr.io/converged-computing/fluxbind-dra-driver:hwloc
    resources: 
       claims: 
         - name: pod-resources